[package]
name = "ds210projectenron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.3"

[[bin]]
name = "enron"
path = "src/enron.rs"



